from setuptools import setup, find_packages

setup(
    name="edgartools",
    description="Navigate Edgar filings with ease",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Dwight Gunning",
    author_email="dgunning@gmail.com",
    license="MIT",
    url="https://github.com/dgunning/edgartools",
    project_urls={
        "Documentation": "https://dgunning.github.io/edgartools/",
        "Issues": "https://github.com/dgunning/edgartools/issues",
        "Source": "https://github.com/dgunning/edgartools",
    },
    python_requires=">=3.9",
    packages=find_packages(exclude=["tests*", "docs*", "notebooks*"]),
    include_package_data=True,
    install_requires=[
        "httpx>=0.25.0",
        "pandas>=2.0.0",
        "tabulate>=0.9.0",
        "pyarrow>=17.0.0",
        "beautifulsoup4>=4.10.0",
        "lxml>=4.4",
        "rich>=13.8.0",
        "humanize>=4.0.0",
        "stamina>=24.2.0",
        "orjson>=3.6.0",
        "textdistance>=4.5.0",
        "rank_bm25>=0.2.1",
        "rapidfuzz>=3.5.0",
        "unidecode>=1.2.0",
        "pydantic>=2.0.0",
        "tqdm>=4.62.0",
        "nest-asyncio>=1.5.1",
        "jinja2>=3.1.0",
        "pyrate-limiter>=3.7.1",
        "hishel>=0.1.3"
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
        "License :: OSI Approved :: MIT License",
    ],
)